#build_cloud: DESKTOP-5L77HE9 Docker
#image: Linux-Node
image: Ubuntu1804
# clone_folder: /home/appveyor/projects/
#stack:
 # - python 3.13
init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: whoami
- sh: echo $HOME
#- sh: >-
 #   [[ ! -d "/home/appveyor/projects" ]] && echo "Home Project directory doesn't exist."
#- sh: >-    
 #   [[ ! -d "./appveyor/projects" ]] && echo "Appveyor Project directory doesn't exist."
#- sh: >-
 #   chown -R appveyor: /home/appveyor/projects
- sh: df -h --total
#- sh: ls -laR /appveyor
#- sh: ls -la /home/appveyor
- sh: cat /opt/appveyor/build-agent/appsettings.json
- sh: grep -Po '^sudo.+:\K.*$' /etc/group
#- sh: cat /etc/docker/daemon.json

test_script:
- sh: openssl version
#- sh: sudo apt-get update
- sh: sudo apt-get install --only-upgrade openssl
- sh: openssl version
- sh: |
    python --version
    python -c 'import sys; print (sys.version_info)'
     
- sh: node --version
- sh: ldd --version
#- sh: sudo sed -i '\%http://apt.postgresql.org/pub/repos/apt%d' /etc/apt/sources.list
#- sh: sudo sed -i '\%http://download.virtualbox.org/virtualbox/debian%d' /etc/apt/sources.list
#- sh:  echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
#- sh: apt-get update && apt-get install -y dotnet-sdk-8.0
- sh: dotnet --list-sdks

build: off
