build_cloud: OWEN-THINKPAD Docker
image: Linux-Node
#clone_folder: /home/appveyor/projects/general-linux-testing
init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: cat /opt/appveyor/build-agent/appsettings.json

test_script:
- sh: ldd --version
#- sh: sudo sed -i '\%http://apt.postgresql.org/pub/repos/apt%d' /etc/apt/sources.list
#- sh: sudo sed -i '\%http://download.virtualbox.org/virtualbox/debian%d' /etc/apt/sources.list
#- sh:  echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
#- sh: sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
- sh: dotnet --list-sdks

build: off
