image: Ubuntu

init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD

test_script:
- sh: sudo apt-get update && sudo apt-get install -y dotnet-sdk-8.0
- sh: dotnet --list-sdks

build: off
