#build_cloud: DESKTOP-5L77HE9 Docker
#image: Linux-Node
image: Previous Ubuntu2204
# clone_folder: /home/appveyor/projects/
environment:
  APPVEYOR_SSH_KEY:
    secure: vH28EZ1I2cqPevARx4icFZyDgBPfZUMSxnnwxOVdS906ci6aVnIP6VOk8aLQV/lkhBlhZxdDJWwTnVcMmivYS6FNspA9w2dDt6VuV0NV0YbRwW63/AyMkgZ1ffqp4vYNb2ZzMxvJYSy/mY/dMbFLOxd1MefCbzI3XfoGTKXl0tYTvzy8cNHE9ZgvVXC10/TniENQR+4UsVa68VTSZ5xP8LKWIuYTJ3dWE7r8S/gVmrT0FXt/Xd7VgE7bSY3WaR8YWSMrRFNFAjtv5YWOwTXUluJWq4nT4Bnwfu96EhxlDqE/jzsqoSqHGPDvB+c9cDPZzyPY99N+THgg19luARw1U+v/3TsaMZ2LXjAB8ynS6ifylWLoNFcavTVMfCwDdUaM4SY1RYmdUxluI1BQOvAyrB6pHHFd86UbgMnZHVHW5VOPDxK9vR/FmuPANuaIuDb8y5NDzVpm+SXCBGdlbmH5NSCtdAIquzdBUf0ppJG/dw24Ch7UQmk8SAhEcP0/wEO7uZg4RQDaoebWc0Zubufzy0m0vZAt6h3E5k3bgR59lsJicSS9hGyWXYfvyHA/QFuCY8Ru683fuMhAOvzSWzOuVi9s+Y3YvhhJUotUKUYRJHcwvV7Nyk3hvqOpULEwggTc8aH6XvSwc/7rpr/skFNYjQdMHbLDqeVsj0kZRVB3DG8b3tRcRoHGS7OhACO7uiYVi2BfLZdjh9KvWyNVXGEjx5vX2sFq0LzeJnmgDqZp/THWqxDSVoGtMowzDFSwyMTnO54JAz+IsObH6lqn7Blqabv7sd8x9k8lPNuAXERw4ME+imcQ0h4mTj4bvyyeYfmn5Lrld+nqjU2imj4PAmxjpUAl3ZdxrPAn07LKLLOzJ96XsYO6e1mPfo51f9/d0nQ4D2lDGTWN9iBMu9b7cmaIedMYva7GJaxCntb9Sqx1F7BvRpdCagY9if2Wk/fQJXDdGRddZp+JpiYqnkZngudAFA==
  APPVEYOR_SSH_BLOCK: true
  
#stack:
 # - python 3.13
init:
- appveyor version
- sh: echo $APPVEYOR_BUILD_WORKER_IMAGE
- sh: echo $APPVEYOR_BUILD_WORKER_CLOUD
- sh: whoami
- sh: echo $HOME
#- sh: >-
 #   [[ ! -d "/home/appveyor/projects" ]] && echo "Home Project directory doesn't exist."
#- sh: >-    
 #   [[ ! -d "./appveyor/projects" ]] && echo "Appveyor Project directory doesn't exist."
#- sh: >-
 #   chown -R appveyor: /home/appveyor/projects
- sh: df -h --total
#- sh: ls -laR /appveyor
#- sh: ls -la /home/appveyor
- sh: cat /opt/appveyor/build-agent/appsettings.json
- sh: grep -Po '^sudo.+:\K.*$' /etc/group
#- sh: cat /etc/docker/daemon.json

test_script:
- sh: ls -l $HOME/Qt
#- sh: curl -sflL 'https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-ssh.sh' | bash -e -
- sh: ls -lisa /usr/bin/gcc*
- sh: openssl version
#- sh: sudo apt-get update
- sh: sudo apt-get install --only-upgrade openssl
- sh: sudo apt-get install --reinstall ca-certificates
- sh: curl -v https://sequensis.myget.org/F/tool-packages/auth/9793a328-23d0-4400-afc3-516fb0354bd5/api/v3/index.json

- sh: |
    python --version
    python -c 'import sys; print (sys.version_info)'
     
- sh: node --version
- sh: ldd --version
#- sh: sudo sed -i '\%http://apt.postgresql.org/pub/repos/apt%d' /etc/apt/sources.list
#- sh: sudo sed -i '\%http://download.virtualbox.org/virtualbox/debian%d' /etc/apt/sources.list
#- sh:  echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
#- sh: apt-get update && apt-get install -y dotnet-sdk-8.0
- sh: dotnet --list-sdks

build: off
